
import { DesignStyle } from '../models/design-style';

export const avataaarsDesignStyle: DesignStyle = {
  id: 'avataaars',
  name: 'Avataaars',
  url: 'https://www.npmjs.com/package/avataaars',
  description: 'The core React component for Avataaars Generator developed by Fang-Pen Lin, based on the Sketch library Avataaars designed by Pablo Stanley.',
  license: {
    type: 'MIT',
  },
  properties: [
    {
      id: 'skinColor',
      label: 'Skin Color',
      type: 'color',
      options: [
        { label: 'Tanned', id: 'Tanned', value: '#fd9840' },
        { label: 'Yellow', id: 'Yellow', value: '#f9d15d' },
        { label: 'Pale', id: 'Pale', value: '#fedbb3' },
        { label: 'Light', id: 'Light', value: '#edb98a' },
        { label: 'Brown', id: 'Brown', value: '#cf8b5a' },
        { label: 'Dark Brown', id: 'DarkBrown', value: '#ae5d28' },
        { label: 'Black', id: 'Black', value: '#604335' },
      ],
    },
    {
      id: 'topType',
      label: 'Hair',
      type: 'select',
      options: [
        { label: 'NoHair', id: 'NoHair' },
        { label: 'Eyepatch', id: 'Eyepatch' },
        { label: 'Hat', id: 'Hat' },
        { label: 'Hijab', id: 'Hijab' },
        { label: 'Turban', id: 'Turban' },
        { label: 'WinterHat1', id: 'WinterHat1' },
        { label: 'WinterHat2', id: 'WinterHat2' },
        { label: 'WinterHat3', id: 'WinterHat3' },
        { label: 'WinterHat4', id: 'WinterHat4' },
        { label: 'LongHairBigHair', id: 'LongHairBigHair' },
        { label: 'LongHairBob', id: 'LongHairBob' },
        { label: 'LongHairBun', id: 'LongHairBun' },
        { label: 'LongHairCurly', id: 'LongHairCurly' },
        { label: 'LongHairCurvy', id: 'LongHairCurvy' },
        { label: 'LongHairDreads', id: 'LongHairDreads' },
        { label: 'LongHairFrida', id: 'LongHairFrida' },
        { label: 'LongHairFro', id: 'LongHairFro' },
        { label: 'LongHairFroBand', id: 'LongHairFroBand' },
        { label: 'LongHairNotTooLong', id: 'LongHairNotTooLong' },
        { label: 'LongHairShavedSides', id: 'LongHairShavedSides' },
        { label: 'LongHairMiaWallace', id: 'LongHairMiaWallace' },
        { label: 'LongHairStraight', id: 'LongHairStraight' },
        { label: 'LongHairStraight2', id: 'LongHairStraight2' },
        { label: 'LongHairStraightStrand', id: 'LongHairStraightStrand' },
        { label: 'ShortHairDreads01', id: 'ShortHairDreads01' },
        { label: 'ShortHairDreads02', id: 'ShortHairDreads02' },
        { label: 'ShortHairFrizzle', id: 'ShortHairFrizzle' },
        { label: 'ShortHairShaggyMullet', id: 'ShortHairShaggyMullet' },
        { label: 'ShortHairShortCurly', id: 'ShortHairShortCurly' },
        { label: 'ShortHairShortFlat', id: 'ShortHairShortFlat' },
        { label: 'ShortHairShortRound', id: 'ShortHairShortRound' },
        { label: 'ShortHairShortWaved', id: 'ShortHairShortWaved' },
        { label: 'ShortHairSides', id: 'ShortHairSides' },
        { label: 'ShortHairTheCaesar', id: 'ShortHairTheCaesar' },
        {
          label: 'ShortHairTheCaesarSidePart',
          id: 'ShortHairTheCaesarSidePart',
        },
      ],
    },
    {
      id: 'hairColor',
      label: 'Hair Color',
      type: 'color',
      options: [
        { label: 'Auburn', id: 'Auburn', value: '#ad683e' },
        { label: 'Black', id: 'Black', value: '#423330' },
        { label: 'Blonde', id: 'Blonde', value: '#bd8e56' },
        { label: 'BlondeGolden', id: 'BlondeGolden', value: '#d9bb7f' },
        { label: 'Brown', id: 'Brown', value: '#805449' },
        { label: 'BrownDark', id: 'BrownDark', value: '#5b4641' },
        { label: 'PastelPink', id: 'PastelPink', value: '#f6a2a2' },
        { label: 'Blue', id: 'Blue', value: '#475a68' },
        { label: 'Platinum', id: 'Platinum', value: '#eee0c6' },
        { label: 'Red', id: 'Red', value: '#cf481e' },
        { label: 'SilverGray', id: 'SilverGray', value: '#eae4e4' },
      ],
    },
    {
      id: 'facialHairType',
      label: 'Facial Hair',
      type: 'select',
      options: [
        { label: 'Blank', id: 'Blank' },
        { label: 'BeardMedium', id: 'BeardMedium' },
        { label: 'BeardLight', id: 'BeardLight' },
        { label: 'BeardMajestic', id: 'BeardMajestic' },
        { label: 'MoustacheFancy', id: 'MoustacheFancy' },
        { label: 'MoustacheMagnum', id: 'MoustacheMagnum' },
      ],
    },
    {
      id: 'facialHairColor',
      label: 'Facial Hair Color',
      type: 'color',
      options: [
        { label: 'Auburn', id: 'Auburn', value: '#ad683e' },
        { label: 'Black', id: 'Black', value: '#423330' },
        { label: 'Blonde', id: 'Blonde', value: '#bd8e56' },
        { label: 'BlondeGolden', id: 'BlondeGolden', value: '#d9bb7f' },
        { label: 'Brown', id: 'Brown', value: '#805449' },
        { label: 'BrownDark', id: 'BrownDark', value: '#5b4641' },
        { label: 'Platinum', id: 'Platinum', value: '#eee0c6' },
        { label: 'Red', id: 'Red', value: '#cf481e' },
      ],
    },
    {
      id: 'eyeType',
      label: 'Eyes',
      type: 'select',
      options: [
        { label: 'Close', id: 'Close' },
        { label: 'Cry', id: 'Cry' },
        { label: 'Default', id: 'Default' },
        { label: 'Dizzy', id: 'Dizzy' },
        { label: 'EyeRoll', id: 'EyeRoll' },
        { label: 'Happy', id: 'Happy' },
        { label: 'Hearts', id: 'Hearts' },
        { label: 'Side', id: 'Side' },
        { label: 'Squint', id: 'Squint' },
        { label: 'Surprised', id: 'Surprised' },
        { label: 'Wink', id: 'Wink' },
        { label: 'WinkWacky', id: 'WinkWacky' },
      ],
    },
    {
      id: 'eyebrowType',
      label: 'Eyebrow',
      type: 'select',
      options: [
        { label: 'Angry', id: 'Angry' },
        { label: 'AngryNatural', id: 'AngryNatural' },
        { label: 'Default', id: 'Default' },
        { label: 'DefaultNatural', id: 'DefaultNatural' },
        { label: 'FlatNatural', id: 'FlatNatural' },
        { label: 'RaisedExcited', id: 'RaisedExcited' },
        { label: 'RaisedExcitedNatural', id: 'RaisedExcitedNatural' },
        { label: 'SadConcerned', id: 'SadConcerned' },
        { label: 'SadConcernedNatural', id: 'SadConcernedNatural' },
        { label: 'UnibrowNatural', id: 'UnibrowNatural' },
        { label: 'UpDown', id: 'UpDown' },
        { label: 'UpDownNatural', id: 'UpDownNatural' },
      ],
    },
    {
      id: 'mouthType',
      label: 'Mouth',
      type: 'select',
      options: [
        { label: 'Concerned', id: 'Concerned' },
        { label: 'Default', id: 'Default' },
        { label: 'Disbelief', id: 'Disbelief' },
        { label: 'Eating', id: 'Eating' },
        { label: 'Grimace', id: 'Grimace' },
        { label: 'Sad', id: 'Sad' },
        { label: 'ScreamOpen', id: 'ScreamOpen' },
        { label: 'Serious', id: 'Serious' },
        { label: 'Smile', id: 'Smile' },
        { label: 'Tongue', id: 'Tongue' },
        { label: 'Twinkle', id: 'Twinkle' },
        { label: 'Vomit', id: 'Vomit' },
      ],
    },
    {
      id: 'clotheType',
      label: 'Clothes',
      type: 'select',
      options: [
        { label: 'BlazerShirt', id: 'BlazerShirt' },
        { label: 'BlazerSweater', id: 'BlazerSweater' },
        { label: 'CollarSweater', id: 'CollarSweater' },
        { label: 'GraphicShirt', id: 'GraphicShirt' },
        { label: 'Hoodie', id: 'Hoodie' },
        { label: 'Overall', id: 'Overall' },
        { label: 'ShirtCrewNeck', id: 'ShirtCrewNeck' },
        { label: 'ShirtScoopNeck', id: 'ShirtScoopNeck' },
        { label: 'ShirtVNeck', id: 'ShirtVNeck' },
      ],
    },
    {
      id: 'clotheColor',
      label: 'Clothes Color',
      type: 'color',
      options: [
        { label: 'Black', id: 'Black', value: '#262d33' },
        { label: 'Blue01', id: 'Blue01', value: '#65c8ff' },
        { label: 'Blue02', id: 'Blue02', value: '#5199e5' },
        { label: 'Blue03', id: 'Blue03', value: '#25557d' },
        { label: 'Gray01', id: 'Gray01', value: '#e6e6e6' },
        { label: 'Gray02', id: 'Gray02', value: '#919598' },
        { label: 'Heather', id: 'Heather', value: '#3c4f5d' },
        { label: 'PastelBlue', id: 'PastelBlue', value: '#b1e2ff' },
        { label: 'PastelGreen', id: 'PastelGreen', value: '#a7ffc3' },
        { label: 'PastelOrange', id: 'PastelOrange', value: '#ffdeb5' },
        { label: 'PastelRed', id: 'PastelRed', value: '#f59797' },
        { label: 'PastelYellow', id: 'PastelYellow', value: '#feffb1' },
        { label: 'Pink', id: 'Pink', value: '#ff488e' },
        { label: 'Red', id: 'Red', value: '#ff5d5b' },
        { label: 'White', id: 'White', value: '#ffffff' },
      ],
    },
    {
      id: 'accessoriesType',
      label: 'Accesory',
      type: 'select',
      options: [
        { label: 'Blank', id: 'Blank' },
        { label: 'Kurt', id: 'Kurt' },
        { label: 'Prescription01', id: 'Prescription01' },
        { label: 'Prescription02', id: 'Prescription02' },
        { label: 'Round', id: 'Round' },
        { label: 'Sunglasses', id: 'Sunglasses' },
        { label: 'Wayfarers', id: 'Wayfarers' },
      ],
    },
  ],
};
