
export const topTypes = [
  { label: 'NoHair', id: 'NoHair' },
  { label: 'Eyepatch', id: 'Eyepatch' },
  { label: 'Hat', id: 'Hat' },
  { label: 'Hijab', id: 'Hijab' },
  { label: 'Turban', id: 'Turban' },
  { label: 'WinterHat1', id: 'WinterHat1' },
  { label: 'WinterHat2', id: 'WinterHat2' },
  { label: 'WinterHat3', id: 'WinterHat3' },
  { label: 'WinterHat4', id: 'WinterHat4' },
  { label: 'LongHairBigHair', id: 'LongHairBigHair' },
  { label: 'LongHairBob', id: 'LongHairBob' },
  { label: 'LongHairBun', id: 'LongHairBun' },
  { label: 'LongHairCurly', id: 'LongHairCurly' },
  { label: 'LongHairCurvy', id: 'LongHairCurvy' },
  { label: 'LongHairDreads', id: 'LongHairDreads' },
  { label: 'LongHairFrida', id: 'LongHairFrida' },
  { label: 'LongHairFro', id: 'LongHairFro' },
  { label: 'LongHairFroBand', id: 'LongHairFroBand' },
  { label: 'LongHairNotTooLong', id: 'LongHairNotTooLong' },
  { label: 'LongHairShavedSides', id: 'LongHairShavedSides' },
  { label: 'LongHairMiaWallace', id: 'LongHairMiaWallace' },
  { label: 'LongHairStraight', id: 'LongHairStraight' },
  { label: 'LongHairStraight2', id: 'LongHairStraight2' },
  { label: 'LongHairStraightStrand', id: 'LongHairStraightStrand' },
  { label: 'ShortHairDreads01', id: 'ShortHairDreads01' },
  { label: 'ShortHairDreads02', id: 'ShortHairDreads02' },
  { label: 'ShortHairFrizzle', id: 'ShortHairFrizzle' },
  { label: 'ShortHairShaggyMullet', id: 'ShortHairShaggyMullet' },
  { label: 'ShortHairShortCurly', id: 'ShortHairShortCurly' },
  { label: 'ShortHairShortFlat', id: 'ShortHairShortFlat' },
  { label: 'ShortHairShortRound', id: 'ShortHairShortRound' },
  { label: 'ShortHairShortWaved', id: 'ShortHairShortWaved' },
  { label: 'ShortHairSides', id: 'ShortHairSides' },
  { label: 'ShortHairTheCaesar', id: 'ShortHairTheCaesar' },
  { label: 'ShortHairTheCaesarSidePart', id: 'ShortHairTheCaesarSidePart' },
];