import { Component, Input } from '@angular/core';
import { Model, Package } from '../../../states/packages.state';

@Component({
  selector: 'cf-package-model-viewer',
  template: `
    <div cfBlock="package-model-viewer" *ngIf="model && package">
      <div cfBlock="header">
        <cf-typography
          type="h2"
          cfElem="name"
          [cfMod]="model.name === 'index' ? 'index' : undefined"
        >
          <cf-svg-icon
            src="assets/icons/codicons/symbol-{{
              model.name === 'index' ? 'ruler' : 'misc'
            }}.svg"
          ></cf-svg-icon>
          {{ model.name | cfCase }}
        </cf-typography>
        <cf-typography>
          <ng-container
            *ngIf="model.description; else autogeneratedDescriptionTemplate"
          >
            {{ model.description }}
          </ng-container>
          <ng-template #autogeneratedDescriptionTemplate>
            <ng-container *ngIf="model.name !== 'index'">
              This is the specification for
              {{ model.name | cfCase }}
            </ng-container>
            <ng-container *ngIf="model.name === 'index'">
              This is the index for the
              {{ package.name | cfCase }} module
            </ng-container>
          </ng-template>
        </cf-typography>
      </div>
      <div cfBlock="content">
        <div cfElem="item" *ngIf="model.imports">
          <cf-model-imports-list
            [imports]="model.imports"
          ></cf-model-imports-list>
        </div>

        <div cfElem="item" *ngIf="model.roots">
          <cf-model-roots-list [roots]="model.roots"></cf-model-roots-list>
        </div>

        <div cfElem="item" *ngIf="model.enums">
          <cf-model-enums-list [enums]="model.enums"></cf-model-enums-list>
        </div>

        <div cfElem="item" *ngIf="model.types">
          <cf-model-types-list [types]="model.types"></cf-model-types-list>
        </div>
      </div>
    </div>
  `,
  styles: [
    `
      .header {
        margin-bottom: 1rem;
        .header__name {
          color: var(--color-syntax-file) !important;
          &--index {
            color: var(--color-syntax-ignore) !important;
          }
        }
      }

      .content {
        &__item {
          margin-bottom: 1rem;
        }
      }
    `,
  ],
})
export class PackageModelViewerComponent {
  @Input() package?: Package;
  @Input() model?: Model;
}
